name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Information
        run: ./gradlew project tasks dependencies

  build:
    runs-on: ${{ matrix.os }}
    needs: setup
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [8, 11, 17, 21]

    name: Build Java ${{ matrix.java-version }} / ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assemble publishToMavenLocal

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup

    name: Test Project
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Test
        run: ./gradlew allTests

  publish:
    runs-on: macos-latest
    needs: [build, test]
    name: Publish to Repository
    if: ${{ github.event_name != 'pull_request' }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Publish to Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew clean assemble publish -Psnapshot=true